version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  mysql:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass
    volumes:
      - data:/var/lib/mysql
  worker:
    image: gorse_worker
    restart: unless-stopped
    ports:
      - 8089:8089
    command: --master-host master --master-port 8086 --http-host 0.0.0.0 --http-port 8089
  server:
    image: gorse_server
    restart: unless-stopped
    ports:
      - 8087:8087
    command: --master-host master --master-port 8086 --http-host 0.0.0.0 --http-port 8087
  master:
    image: gorse_master
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - ./config.toml:/etc/config.toml
volumes:
  data:
